language: python

python:
  - "3.4"

services: postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE="questioner.travis_ci_settings"
    - PYTHONPATH="/home/travis/build/AtamaZack/questioner"
    - PIP_USE_MIRRORS=true
  matrix:
    - DJANGO=1.7 DB=postgresql

#commands to install dependencies
install:
  - pip install -q Django==$DJANGO
  - pip install -q -r requirements.txt

before_script:
  - mysql -e 'create database travis_ci_db;'
  - python manage.py syncdb --noinput

#command to run the test suite
script:
  - python manage.py test