
language: python

python:
  - "3.4"

services: postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE="questioner.travis_ci_settings"
    - PYTHONPATH="/home/travis/build/kbjude/questioner"
    - PIP_USE_MIRRORS=true
  matrix:
    - Django==2.0.13 DB=postgresql

#commands to install dependencies
install:
  - pip install -r requirements.txt

before_script:questioner
  - psql -c 'create database travis_ci_db;' -U postgres

#command to run the test suite
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python -m pytest --cov
